### ISSUE TITLE
Actions fail when used as a dependency in other repositories

### ISSUE THREAD

**Issue by beescuit** [advanced-security/codeql-bundle-action#11]
If you copy & paste the example "Build custom bundle" action from the readme into a new repository, the following error occurs:

```
Run advanced-security/codeql-bundle-action/download-bundle@v2
Run download-bundle/download-bundle.sh
/home/runner/work/_temp/xxxxxxxxx.sh: line 1: download-bundle/download-bundle.sh: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by rvermeulen** [comment]
Hi @beescuit,

Thanks for the report. Could you share some more information on your workflow?
We are testing the actions using https://github.com/advanced-security/codeql-bundle-action/blob/main/.github/workflows/test-create-bundle.yml and the [last run](https://github.com/advanced-security/codeql-bundle-action/actions/runs/7455370937) doesn't have the issue you describe.
