### ISSUE TITLE
Support separated bundles for each target platform

### ISSUE THREAD

**Issue by lcartey** [advanced-security/codeql-bundle-action#5]
The bundle action currently customizes the multi-platform bundle. This ensures the customized bundle is compatible with all supported platforms, but does mean the customized bundle is larger than necessary.

We should add an option to fetch and generate platform specific bundles, so that we can minimize the deployment size.

**Comment by rvermeulen** [comment]
Since version [2.0](https://github.com/advanced-security/codeql-bundle-action/tree/v2.0) we support the creation of platform specific bundles to reduce the deployment size.
